CREATE TABLE IF NOT EXISTS public.car_marks
(
    mark_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    mark_name character varying(255),
    CONSTRAINT car_mark_pkey PRIMARY KEY (mark_id)
);

CREATE TABLE IF NOT EXISTS public.car_models
(
    model_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    model_name character varying(255),
    car_mark_id integer,
    CONSTRAINT car_model_pkey PRIMARY KEY (model_id),
    CONSTRAINT fk_car_model_car_mark_id FOREIGN KEY (car_mark_id)
        REFERENCES public.car_marks (mark_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.regions
(
    region_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    region_number character varying(255),
    CONSTRAINT regions_pkey PRIMARY KEY (region_id),
    CONSTRAINT unique_region_number UNIQUE (region_number)
);

CREATE TABLE IF NOT EXISTS public.cars
(
    car_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount_of_owners integer,
    body_type character varying(255),
    car_number character varying(255),
    color character varying(255),
    date_added timestamp without time zone,
    mileage integer,
    year character varying(255),
    car_mark_id integer,
    car_model_id integer,
    region_id integer,
    CONSTRAINT cars_pkey PRIMARY KEY (car_id),
    CONSTRAINT uk_car_number_and_region UNIQUE (car_number, region_id),
    CONSTRAINT fk_car_car_mark FOREIGN KEY (car_mark_id)
        REFERENCES public.car_marks (mark_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_car_regions FOREIGN KEY (region_id)
        REFERENCES public.regions (region_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_car_car_models FOREIGN KEY (car_model_id)
        REFERENCES public.car_models (model_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)




